### ISSUE TITLE
Empty alert message immediately after bfast launch

### ISSUE THREAD

**Issue by dfguerrerom** [12rambau/bfast_gpu#36]
Just after clicking over the launch button, the alert widget appears without any info, causing the sense that something is not working, could we provide a message while the progress bar starts?

**Comment by 12rambau** [comment]
It is already coded (https://github.com/12rambau/bfast_gpu/commit/2f4540bd14c2af70720f24229833fb43834155e8), I just need the release of the next version of SEPAL in prod to use it. 

as the `master` branch is based on my fork of the bfast lib I cannot install it without the virtual env fonctionality
